import { copyFile, mkdir, mkdtemp, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const output = join(root, "dist");
const marker = ".ruta-clara-build";
const files = ["index.html", "style-v2.css", "app.js", "lib/model.js", "lib/workflow.js"];
const staging = await mkdtemp(join(root, ".dist-tmp-"));

function version(content) {
  return createHash("sha256").update(content).digest("hex").slice(0, 12);
}

function replaceOnce(source, before, after) {
  if (source.split(before).length !== 2) throw new Error(`Expected one reference to ${before}`);
  return source.replace(before, after);
}

try {
  const staticFiles = ["style-v2.css", "lib/model.js", "lib/workflow.js"];
  const versions = {};
  for (const file of staticFiles) {
    const destination = join(staging, file);
    await mkdir(dirname(destination), { recursive: true });
    await copyFile(join(root, file), destination);
    versions[file] = version(await readFile(join(root, file)));
  }

  let app = await readFile(join(root, "app.js"), "utf8");
  for (const file of ["lib/model.js", "lib/workflow.js"]) {
    app = replaceOnce(app, `from "./${file}"`, `from "./${file}?v=${versions[file]}"`);
  }
  await writeFile(join(staging, "app.js"), app);

  let html = await readFile(join(root, "index.html"), "utf8");
  html = replaceOnce(html, 'href="./style-v2.css"', `href="./style-v2.css?v=${versions["style-v2.css"]}"`);
  html = replaceOnce(html, 'src="./app.js"', `src="./app.js?v=${version(app)}"`);
  await writeFile(join(staging, "index.html"), html);
  await writeFile(join(staging, marker), "Generated by scripts/build.mjs.\n");

  let outputExists = false;
  try {
    await stat(output);
    outputExists = true;
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  if (outputExists) {
    try {
      await readFile(join(output, marker));
    } catch (error) {
      if (error.code === "ENOENT") {
        throw new Error("dist/ exists without a build marker; refusing to overwrite it.");
      }
      throw error;
    }
    await rm(output, { recursive: true });
  }

  await rename(staging, output);
  console.log(`Built ${files.length} public files in dist/`);
} finally {
  await rm(staging, { recursive: true, force: true });
}
