import { copyFile, mkdir, mkdtemp, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const output = join(root, "dist");
const marker = ".ruta-clara-build";
const files = ["index.html", "style-v2.css", "app.js", "lib/model.js", "lib/workflow.js"];
const staging = await mkdtemp(join(root, ".dist-tmp-"));

try {
  for (const file of files) {
    const destination = join(staging, file);
    await mkdir(dirname(destination), { recursive: true });
    await copyFile(join(root, file), destination);
  }
  await writeFile(join(staging, marker), "Generated by scripts/build.mjs.\n");

  let outputExists = false;
  try {
    await stat(output);
    outputExists = true;
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  if (outputExists) {
    try {
      await readFile(join(output, marker));
    } catch (error) {
      if (error.code === "ENOENT") {
        throw new Error("dist/ exists without a build marker; refusing to overwrite it.");
      }
      throw error;
    }
    await rm(output, { recursive: true });
  }

  await rename(staging, output);
  console.log(`Built ${files.length} public files in dist/`);
} finally {
  await rm(staging, { recursive: true, force: true });
}
